language: rust
sudo: false
cache:
  - cargo
rust:
  - stable
before_script:
  - (cargo install mdbook --vers 0.3.0 --force || true)
script:
  - mdbook build
deploy:
  provider: pages
  local-dir: book
  skip_cleanup: true
  github_token: $GH_DEPLOY_TOKEN
  keep_history: true
  on:
    branch: master